### ISSUE TITLE
Suggest adding keywords to github project description

### ISSUE THREAD

**Issue by samoconnor** [staticfloat/Nettle.jl#56]
The github project description is currently: "Julia package for libnettle"
This is the text that shows up under "Nettle" at http://pkg.julialang.org.

Minor suggestion: change the description to:  "Julia package for libnettle (SHA1, SHA256, MD5 etc)"

This would make the package more discoverable to someone who knows they want to compute a common hash, but does not know anything about libnettle.

**Comment by samoconnor** [comment]
bump!

See what LibArchive.jl has put in their description: https://github.com/yuyichao/LibArchive.jl

**Comment by staticfloat** [comment]
Hey Sam, sorry that this has taken so long.  For some reason, github doesn't email me when people perform actions on repositories that I own. I have to comment on a thread in order to see it, or be pinged by someone via @staticfloat.  In the future, please do not be shy of drawing my attention by pinging me.

I've updated the description, does what I've added look good?

**Comment by samoconnor** [comment]
nice one @staticfloat 
Nettle.jl is now getting a workout at https://github.com/samoconnor/AWSCore.jl

**Comment by staticfloat** [comment]
Excellent, so glad that you find things like this helpful!
